In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

ModuleNotFoundError: No module named 'matplotlib'

In [4]:
import pandas as pd

class AlphaVantage:
    ALPHA_VANTAGE_API_KEY = "5QQ3NMDSVUMS1EDX"
    BASE_API_PATH = "https://www.alphavantage.co/query?"
    
    def query(self,*args, **kwargs):
        # https://www.alphavantage.co/documentation/
        if(not kwargs.get("datatype")):
            kwargs["datatype"] = "csv"
        kwargs["apikey"] = self.BASE_API_PATH
        return pd.read_csv(self.get_query_path(kwargs))
    
    def get_query_path(self,kwargs):
        resulted_query_path = self.BASE_API_PATH
        for key, value in kwargs.items():
            resulted_query_path += "{0}={1}&".format(key,value)
        print(resulted_query_path)
        return resulted_query_path

AV = AlphaVantage()
AV.query(function="TIME_SERIES_DAILY", symbol="IBM",)

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&datatype=csv&apikey=https://www.alphavantage.co/query?&

     timestamp    open      high     low   close   volume
0   2022-08-05  131.25  132.6700  131.07  132.48  2586519
1   2022-08-04  132.15  132.2866  131.02  131.64  3179789
2   2022-08-03  131.82  132.8620  131.32  132.34  3088532
3   2022-08-02  132.20  132.7800  130.51  131.81  4403633
4   2022-08-01  130.75  132.7000  130.70  132.04  4142099
..         ...     ...       ...     ...     ...      ...
95  2022-03-21  129.00  129.7400  127.40  128.10  3379393
96  2022-03-18  127.38  128.9300  126.37  128.76  7400216
97  2022-03-17  127.10  128.2900  126.53  127.96  3671903
98  2022-03-16  126.50  127.2842  124.71  127.04  4292845
99  2022-03-15  124.00  125.9398  123.22  125.64  4021228

[100 rows x 6 columns]